# Generated by Django 2.2.7 on 2020-05-05 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmeet.Course'),
        ),
        migrations.CreateModel(
            name='StudentProfileYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmeet.StudentProfile')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmeet.Year')),
            ],
        ),
    ]
