# Generated by Django 3.0.6 on 2020-05-27 16:20

from django.db import migrations
from helpers import migrate_run_sql


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0002_auto_storedprocedure'),
    ]

    operations = [
        migrations.RunPython(
            migrate_run_sql.run_sql(
                '''                
                LOCK TABLES `qmeet_academicyear` WRITE;
                INSERT INTO `qmeet_academicyear` VALUES (1,'First year'),(2,'Second year'),(3,'Final year');
                UNLOCK TABLES;

                LOCK TABLES `qmeet_categories` WRITE;
                INSERT INTO `qmeet_categories` VALUES (1,'Gaming'),(2,'Food'),(3,'Music'),(4,'Sports'),(5,'Entertainment'),(6,'Studying'),(7,'Creative arts'),(8,'Technology');
                UNLOCK TABLES;

                LOCK TABLES `qmeet_department` WRITE;
                INSERT INTO `qmeet_department` VALUES (1,'Institute of Bioengineering'),(2,'School of Biological and Chemical Sciences'),(3,'School of Electronic Engineering and Computer Science'),(4,'School of Engineering and Materials Science'),(5,'School of Mathematical Sciences'),(6,'School of Physics and Astronomy'),(7,'Materials Research Institute (MRI)');
                UNLOCK TABLES;

                LOCK TABLES `qmeet_course` WRITE;
                INSERT INTO `qmeet_course` VALUES (1,'Computer Science','Computer Science description',3),(2,'Mathematics','Mathematics description',5);
                UNLOCK TABLES;

                LOCK TABLES `qmeet_module` WRITE;
                INSERT INTO `qmeet_module` VALUES (1,'Calculus 1','MTHC1','Calculus description'),(2,'Calculus 2','MTHC2','Calculus 2 description'),(3,'Intro to probability','MTHP1','Intro to probability description'),(4,'Intro to stats','MTHS1','Intro to stats description'),(5,'Procedural programming','ECSPP','Procedural programming description'),(6,'Database (LAB)','CSDDBM-1L','Build on your database knowledge by actually trying it out'),(7,'Research','ECSR','Research description'),(8,'Information and systems analysis','ECSISA','Information and systems analysis description'),(9,'Logic and discrete structures','ECSLDS','Logic and discrete structures description'),(10,'Introduction to Python Development','CSDPY-1','Introduction to python eco-system'),(11,'Python Development (LAB)','CSDPYL','Apply your Python theory into real world examples'),(12,'Operating Systems','CSDOS-1','Introduction to Operating systems'),(13,'Database Theory','CSDDBM-1','Understanding the principle of Databases');
                UNLOCK TABLES;

                LOCK TABLES `qmeet_coursemodules` WRITE;
                INSERT INTO `qmeet_coursemodules` VALUES (1,1,5),(2,1,7),(3,1,8),(4,1,9),(5,2,1),(6,2,2),(7,2,3),(8,2,4),(9,1,10),(10,1,11),(11,1,12),(12,1,13),(13,1,6);
                UNLOCK TABLES;

                LOCK TABLES `qmeet_semester` WRITE;
                INSERT INTO `qmeet_semester` VALUES (1,'1st Semester'),(2,'2nd Semester');
                UNLOCK TABLES;

                LOCK TABLES `qmeet_semestermodule` WRITE;
                INSERT INTO `qmeet_semestermodule` VALUES (1,9,11,'Monday','Mon',10,1),(2,11,12,'Wednesday','Wed',12,1),(3,14,15,'Monday','Mon',11,1),(4,14,16,'Thursday','Thu',13,1),(5,12,13,'Friday','Fri',6,1),(6,10,12,'Tuesday','Tue',9,1),(7,10,11,'Monday','Mon',1,1),(8,12,14,'Tuesday','Tue',2,1),(9,15,16,'Tuesday','Tue',3,1),(10,9,10,'Wednesday','Wed',4,1);
                UNLOCK TABLES;
                '''
            )
        )
    ]
