# Generated by Django 3.0.6 on 2020-05-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0002_semestermodule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestermodule',
            name='end_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semestermodule',
            name='start_hour',
            field=models.IntegerField(default=0),
        ),
    ]
