# Generated by Django 2.2.7 on 2020-05-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0002_auto_20200505_0244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Year',
            new_name='AcademicYear',
        ),
    ]
