# Generated by Django 3.0.6 on 2020-05-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0002_studentprofile_display_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=100)),
            ],
        ),
    ]
