# Generated by Django 3.0.6 on 2020-05-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0002_studentprofile_display_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='display_picture',
        ),
    ]
