# Generated by Django 2.2.7 on 2020-04-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0003_student_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='test',
        ),
    ]
