# Generated by Django 3.0.6 on 2020-05-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0003_selectedcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedcategories',
            name='id',
        ),
        migrations.AlterField(
            model_name='selectedcategories',
            name='categories',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
