# Generated by Django 3.0.6 on 2020-05-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0003_auto_20200516_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestermodule',
            name='abbreviated_day',
            field=models.CharField(default='mon', max_length=3),
            preserve_default=False,
        ),
    ]
