# Generated by Django 2.2.7 on 2020-04-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0004_remove_student_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
