# Generated by Django 2.2.7 on 2020-04-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0005_remove_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
