# Generated by Django 3.0.6 on 2020-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0005_auto_qmeet_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='display_picture',
            field=models.ImageField(blank=True, default='default-avatar.jpg', upload_to='images/'),
        ),
    ]
