# Generated by Django 2.2.7 on 2020-05-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0005_remove_studentprofile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='categories',
            field=models.ManyToManyField(through='qmeet.StudentCategories', to='qmeet.Categories'),
        ),
        migrations.AlterField(
            model_name='studentcategories',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='qmeet.Categories'),
        ),
    ]
