# Generated by Django 3.0.6 on 2020-05-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0006_auto_20200526_0805'),
    ]

    operations = [
        migrations.RunSQL(
            sql = '''
            CREATE DEFINER=`qmeet` PROCEDURE `SP_SplitString` (Value longtext) 
            BEGIN 
                DECLARE front TEXT DEFAULT NULL; 
                DECLARE frontlen INT DEFAULT NULL; 
                DECLARE TempValue TEXT DEFAULT NULL; 
                iterator:
                LOOP  
                IF LENGTH(TRIM(Value)) = 0 OR Value IS NULL THEN
                LEAVE iterator;
                END IF;
                SET front = SUBSTRING_INDEX(Value,',',1);
                SET frontlen = LENGTH(front);
                SET TempValue = TRIM(front);
                INSERT INTO qmeet.qmeet_selectedcategories (categories) VALUES (TempValue);
                SET Value = INSERT(Value,1,frontlen + 1,'');
                END LOOP;
            END
        ''')
    ]
