# Generated by Django 2.2.7 on 2020-05-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0006_auto_20200511_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='categories',
        ),
        migrations.AlterField(
            model_name='studentcategories',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmeet.Categories'),
        ),
    ]
