# Generated by Django 3.0.6 on 2020-05-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0007_auto_qmeet_stored_procs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedCategories',
        ),
    ]
