# Generated by Django 2.2.7 on 2020-05-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0008_studentprofile_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='categories',
        ),
    ]
