# Generated by Django 3.0.6 on 2020-05-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0010_auto_20200521_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='display_picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
