# Generated by Django 3.0.6 on 2020-05-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0011_auto_storedproc_filtersp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedCategories',
        ),
    ]
