# Generated by Django 3.0.6 on 2020-05-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0012_delete_selectedcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCategories',
            fields=[
                ('categories', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
