# Generated by Django 3.0.6 on 2020-05-26 21:24

from django.db import migrations
from helpers import migrate_run_sql


class Migration(migrations.Migration):

    dependencies = [
        ('qmeet', '0013_selectedcategories'),
    ]

    operations = [
        migrations.RunPython(
            migrate_run_sql.run_sql(
            '''
            DELIMITER $$
            CREATE DEFINER=`qmeet` PROCEDURE `GetFriendsSP`(
                IN UserID integer
            )
            BEGIN
                select qs2.id, qs2.username from qmeet_student qs 
                join qmeet_studentprofile qsp on qs.id = qsp.student_id
                join qmeet_studentprofile_friends qspf on qsp.id = qspf.from_studentprofile_id
                join qmeet_studentprofile qsp2 on qspf.to_studentprofile_id = qsp2.id
                join qmeet_student qs2 on qsp2.student_id = qs2.id
                where qs.id = UserID;
            END$$
            DELIMITER ;
            '''
            )
        ),
        migrations.RunPython(
            migrate_run_sql.run_sql(
            '''
            DELIMITER $$
            CREATE DEFINER=`qmeet` PROCEDURE `GetTimetableForUserSP`(
                IN StudentId integer
            )
            BEGIN
                SELECT 	qs.name as semester_name
                , 		qm.name as module_name
                ,		qsm.start_hour
                ,		qsm.end_hour
                ,		LOWER(qsm.abbreviated_day) as abbreviated_day
                , 		qsm.end_hour - qsm.start_hour as duration 
                FROM qmeet.qmeet_semester qs
                JOIN qmeet.qmeet_semestermodule qsm ON qsm.semester_id = qs.id
                JOIN qmeet.qmeet_module qm ON qm.id = qsm.module_id
                JOIN qmeet.qmeet_coursemodules qcm ON qcm.module_id = qm.id
                JOIN qmeet.qmeet_studentprofile qsp ON qsp.course_id = qcm.course_id
                JOIN week_day_order wdo ON wdo.day = qsm.day
                WHERE qsp.student_id = StudentId
                ORDER BY qsm.start_hour, wdo.order;
            END$$
            DELIMITER ;
            '''
            )
        ),
        migrations.RunPython(
            migrate_run_sql.run_sql(
            '''
                DELIMITER $$
                CREATE DEFINER=`qmeet`@`%` PROCEDURE `GetUnreadMessagesSP`(
                    IN UserID int(10)
                )
                BEGIN
                    select count(*) as 'un_read', subject, sender_id from django_messages_message
                    where read_at is null and recipient_id=UserID;
                END$$
                DELIMITER ;
            '''
            )
        )
    ]
